%  Consultant Company, Version 4

function [pns] = cc_v4_pdf()

pns.PN_name = 'Consultant Company Version 4';
pns.set_of_Ps = {'p2', ...
                 'p3a', 'p5a', 'p6a', ...
                 'p3b', 'p5b', 'p6b', ...
                 'p3c', 'p5c', 'p6c', ...
                  'p4' ...
                  };
pns.set_of_Ts = {'t1', ...
                 't2a', 't3a', 'twa','t4a', ...
                 't2b', 't3b', 'twb','t4b', ...
                 't2c', 't3c', 'twc','t4c'  ...
                 }; 
pns.set_of_As = {'t1','p2',1 , ...
                 'p2','t2a',1, 't2a','p3a',1, 'p3a','t3a',1, 't3a','p4',1 ,...
                 'p3a','twa',1 ,'twa','p3a',1 , ...
                 't3a','p5a',1,'p5a','t4a',1, 't4a','p6a',1 , 'p6a','t2a',1, ...
                 'p2','t2b',1, 't2b','p3b',1, 'p3b','t3b',1, 't3b','p4',1 ,...
                 'p3b','twb',1 ,'twb','p3b',1 , ...
                 't3b','p5b',1,'p5b','t4b',1, 't4b','p6b',1 , 'p6b','t2b',1, ...                 
                 'p2','t2c',1, 't2c','p3c',1, 'p3c','t3c',1, 't3c','p4',1 ,...
                 'p3c','twc',1 ,'twc','p3c',1 , ...
                 't3c','p5c',1,'p5c','t4c',1, 't4c','p6c',1 , 'p6c','t2c',1  ...                 
                 };
